<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvXzrkN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvXzrkN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFvXzrkN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFvXzrkN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFvXzrkN\App_KernelDevDebugContainer([
    'container.build_hash' => 'FvXzrkN',
    'container.build_id' => '4327a65f',
    'container.build_time' => 1737304369,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvXzrkN');
