services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfileFrontendAMG
    ports:
      - "3000:5173"
    container_name: frontendAMG
    networks:
      - redwebAMG

  backend:
    build:
      context: ./backend
      dockerfile: dockerfileBackendAMG
    ports:
      - "8000:8000"
    container_name: backendAMG
    networks:
      - redwebAMG

  web:
    build:
      context: ./web
      dockerfile: dockerfileWebAMG
    ports:
      - "80:80"
    container_name: webAMG
    networks:
      - redwebAMG

networks:
  redwebAMG:
    driver: bridge